version: '3.3'

services:
  db:
    image: postgres:14.9-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - network

  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    entrypoint: /app/docker/backend/django-entrypoint.sh
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - static_value:/app/backend/static/
      - media_value:/app/backend/media/
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    networks:
      - network

  nginx:
    image: nginx:1.25.0-alpine
    depends_on:
      - db
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/app/backend/static/
      - media_value:/app/backend/media/
    env_file:
    - .env
    networks:
      - network

volumes:
  postgres_data:
  static_value:
  media_value:

networks:
  network:
    driver: bridge
