# Generated by Django 3.2.18 on 2023-09-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='test completed at'),
        ),
        migrations.AlterField(
            model_name='test',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='test started at'),
        ),
    ]
