# Generated by Django 3.2.18 on 2023-09-17 08:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('name', models.CharField(max_length=255, verbose_name="indicator's name")),
                ('description', models.TextField(blank=True, null=True, verbose_name="indicator's description")),
            ],
            options={
                'verbose_name': 'indicators',
                'verbose_name_plural': 'indicators',
            },
        ),
        migrations.CreateModel(
            name='IndicatorMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('indicator_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.indicator')),
            ],
            options={
                'verbose_name': 'indicator - metric pair',
                'verbose_name_plural': 'indicator - metric pairs',
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('name', models.CharField(max_length=255, verbose_name="metric's name")),
                ('description', models.TextField(blank=True, null=True, verbose_name="metric's description")),
                ('unit', models.CharField(max_length=255, verbose_name="metric's unit")),
            ],
            options={
                'verbose_name': 'metric',
                'verbose_name_plural': 'metrics',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('score', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='score')),
                ('indicator_metric_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.indicatormetric')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='public.test')),
            ],
            options={
                'verbose_name': 'score',
                'verbose_name_plural': 'scores',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('min_score', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='minimal score')),
                ('max_score', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='maximal score')),
                ('indicator_metric_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.indicatormetric')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='indicatormetric',
            name='metric_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.metric'),
        ),
    ]
