# Generated by Django 3.2.18 on 2023-09-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_null_value_for_datetime_field_in_test'),
        ('indicators', '0002_uniqueness_for_indicator_metric_pair_in_reference'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('indicator_metric_id', 'test_id')},
        ),
    ]
